# Generated by Django 4.2.1 on 2023-10-02 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('luck', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stats')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('app.stats',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stats')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('app.stats',),
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('stats_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stats')),
                ('name', models.CharField(max_length=50)),
                ('required_level', models.PositiveIntegerField()),
            ],
            bases=('app.stats',),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stuff')),
            ],
            bases=('app.stuff',),
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stuff')),
            ],
            bases=('app.stuff',),
        ),
        migrations.CreateModel(
            name='Gantelet',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stuff')),
            ],
            bases=('app.stuff',),
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stuff')),
            ],
            bases=('app.stuff',),
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stuff')),
            ],
            bases=('app.stuff',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('stuff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.stuff')),
            ],
            bases=('app.stuff',),
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('weapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.weapon')),
            ],
            bases=('app.weapon',),
        ),
        migrations.CreateModel(
            name='Spear',
            fields=[
                ('weapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.weapon')),
            ],
            bases=('app.weapon',),
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('weapon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.weapon')),
            ],
            bases=('app.weapon',),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classe')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.race')),
                ('armor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.armor')),
                ('boots', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.boots')),
                ('helmet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.helmet')),
                ('left_gantelet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_gantelet', to='app.gantelet')),
                ('pant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pant')),
                ('right_gantelet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_gantelet', to='app.gantelet')),
            ],
        ),
    ]
