# Generated by Django 4.2.1 on 2023-10-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': 'Armure', 'verbose_name_plural': 'Armures'},
        ),
        migrations.AlterModelOptions(
            name='boots',
            options={'verbose_name': 'Botte', 'verbose_name_plural': 'Bottes'},
        ),
        migrations.AlterModelOptions(
            name='bow',
            options={'verbose_name': 'Arc', 'verbose_name_plural': 'Arcs'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Personnage', 'verbose_name_plural': 'Personnages'},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='gantelet',
            options={'verbose_name': 'Gantelet', 'verbose_name_plural': 'Gantelets'},
        ),
        migrations.AlterModelOptions(
            name='helmet',
            options={'verbose_name': 'Casque', 'verbose_name_plural': 'Casques'},
        ),
        migrations.AlterModelOptions(
            name='pant',
            options={'verbose_name': 'Pantalon', 'verbose_name_plural': 'Pantalons'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Race', 'verbose_name_plural': 'Races'},
        ),
        migrations.AlterModelOptions(
            name='spear',
            options={'verbose_name': 'Lance', 'verbose_name_plural': 'Lances'},
        ),
        migrations.AlterModelOptions(
            name='sword',
            options={'verbose_name': 'Épée', 'verbose_name_plural': 'Épées'},
        ),
    ]
