# Generated by Django 4.2.1 on 2023-10-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_amulet_belt_ring_stuff_picture_alter_character_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='amulet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.amulet', verbose_name='Amulette'),
        ),
        migrations.AddField(
            model_name='character',
            name='belt',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.belt', verbose_name='Ceinture'),
        ),
        migrations.AddField(
            model_name='character',
            name='ring',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ring', verbose_name='Anneau'),
        ),
    ]
