# Generated by Django 4.2.1 on 2023-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_character_amulet_character_belt_character_ring'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/classe'),
        ),
        migrations.AddField(
            model_name='race',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/races'),
        ),
    ]
