# Generated by Django 4.2.1 on 2023-10-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_classe_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.weapon', verbose_name='arme'),
        ),
    ]
