# Generated by Django 4.2.1 on 2023-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_character_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='niveau'),
        ),
    ]
